substitutions:
  # Name the device and it's entities
  device: LivingRoomSensors
  device_name: LivingRoomSensors
  
esphome:
  name: living_room_sensors

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Z8HPoGusBZnKDvGxfLb8vUXGRJ8FzlyM+2Hsrc8V92U="

ota:
  password: "9475287d1013ca025a95824064344da7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Test Fallback Hotspot"
    password: "eDWPhQ5M5S0j"

captive_portal:

# external_components:
#   - source: github://ryanh7/esphome-custom-components
#     components: [ cem5855h ]

# uart:
#   id: uart_1
#   baud_rate: 115200
#   rx_pin: GPIO9 #你的RX引脚

# binary_sensor: 
#   - platform: gpio 
#     pin: GPIO21
#     name: test111 
#     device_class: motion
#     id: test111
  # - platform: cem5855h
  #   id: test123
  #   uart_id: uart_1
  #   threshold: #（可选）触发移动的阈值，支持数字或者Number(esphome)
  #     moving: 250 #示例配置-数字
  #     occupancy: #示例配置-esphome number
  #       name: "test123_occ"
  #       value: 250 #阈值
  #       min_value: 10 #可调节的最小阈值
  #       max_value: 99999 #可调节的最大阈值
  #       step: 10 #单步调节量
  #   moving: #（可选）有人移动传感器
  #     id: test123_mov
  #     name: test123_mov
  #     filters:
  #       - delayed_off: 3s
  #   occupancy: #（可选）有人静止传感器
  #     id: test123_occ
  #     name: test123_occ
  #     filters:
  #       - delayed_off: 3s
  #   motion: #（可选）人在传感器
  #     id: test123_motion
  #     name: test123_motion
  #     filters:
  #       - delayed_off: 3s

i2c:
  # sda: GPIO21                    #RXD
  # scl: GPIO22                    #TXD
  # scan: true

# sensor:
#   - platform: bh1750
#     id: illuminance
#     name: "室外光照度"
#     address: 0x23
#     update_interval: 2s

external_components:
  - source: github://snowyu/esphome-components

amg88xx:
  ir_camera:
    name: amg8833_1_ir_camera
  device_temperature:
    name: amg8833_1_device_temperature

switch:
  - platform: gpio
    pin: GPIO17
    # inverted: true
    name: "ESP32S-body light"
    id: motion_02_light

sensor:
  - platform: adc
    pin: GPIO34
    name: test1
    id: test1
    unit_of_measurement: "V"